### PR TITLE
Add ability to have different encryption keys on a per user basis

### PR DESCRIPTION
**Pull request by heskethw**
I wanted the ability to create a different key on a per user basis.

I've added an optional user guid parameter, which could be used for separating anything, but in my case is a user's unique id.

Not being a security expert, for me, having different keys per user should make it harder for someone to break the encryption of all the data using brute force, since you wouldn't know which data is encrypted with which key.

Happy to discuss this, but I think it's a useful addition.

### CODE REVIEW

**Comment by cmatskas** [comment]
Hi William,
I haven't forgotten about your PR. I just need to find some time to review the changes.
Thanks for your patience, CM



On Wed, Mar 16, 2016 at 4:11 AM -0700, "William Hesketh" <notifications@github.com> wrote:












I wanted the ability to create a different key on a per user basis.



I've added an optional user guid parameter, which could be used for separating anything, but in my case is a user's unique id.



Not being a security expert, for me, having different keys per user should make it harder for someone to break the encryption of all the data using brute force, since you wouldn't know which data is encrypted with which key.



Happy to discuss this, but I think it's a useful addition.



You can view, comment on, or merge this pull request online at:


  https://github.com/cmatskas/Azure.Security/pull/3

Commit Summary

  Added unique symmetric key per user facility
  Made user id optional
  Fixed test tear down
  Added more tests


File Changes

  
    M
    Azure.Security.Tests/Azure.Security.Tests.csproj
    (3)
  
  
    M
    Azure.Security.Tests/AzureCryptoTests.cs
    (55)
  
  
    M
    Azure.Security.Tests/EncryptionHelperTests.cs
    (57)
  
  
    M
    Azure.Security.Tests/RsaHelperTests.cs
    (11)
  
  
    M
    Azure.Security.Tests/SymmetricKeyTableManagerTests.cs
    (31)
  
  
    M
    Azure.Security/Azure.Security.csproj
    (1)
  
  
    M
    Azure.Security/AzureCrypto.cs
    (42)
  
  
    M
    Azure.Security/EncryptionHelper.cs
    (53)
  
  
    M
    Azure.Security/Interfaces/ICrypto.cs
    (13)
  
  
    M
    Azure.Security/Interfaces/IEncryptionHelper.cs
    (12)
  
  
    M
    Azure.Security/Interfaces/IRsaHelper.cs
    (4)
  
  
    M
    Azure.Security/Interfaces/ISymmetricKeyCache.cs
    (5)
  
  
    M
    Azure.Security/RsaHelper.cs
    (11)
  
  
    A
    Azure.Security/SymmetricAlgorithmItem.cs
    (13)
  
  
    M
    Azure.Security/SymmetricKey.cs
    (2)
  
  
    M
    Azure.Security/SymmetricKeyCache.cs
    (28)
  


Patch Links:

  https://github.com/cmatskas/Azure.Security/pull/3.patch
  https://github.com/cmatskas/Azure.Security/pull/3.diff

**Comment by heskethw** [comment]
Hi Christos, No worries, I know how hard it is to find time to work on things that aren't a priority. 

We're about to roll this out to our staging area though, it all seems to be working correctly. 

Let me know if you have any questions, happy to discuss.

**Comment by heskethw** [comment]
Just FYI, this has some performance problems when scaling to a large number of rows in the Azure Table. I'm working on a fix for us, and I'll update when I get the chance.

**Comment by heskethw** [comment]
Hi Christos, I'm not sure if you remember this pull request, but I've finally found the time to finish the code. 

I've updated the test project and tidied up the changes I made to the project. The tests are now passing properly and the per user keys work well for us. I've been using this in production now for almost two years without problem, it seems like the performance changes I made worked correctly.

Happy holidays! 🎄

**Comment by cmatskas** [comment]
Hi @heskethw Thanks for the PR.. Apologies it took so long to merge this 👍 I'll create a new NuGet package over the next few days

**Comment by heskethw** [comment]
No worries, glad to help!

**Pull request merged**
